ALTER TABLE jobs ADD COLUMN queue_global_ahead INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN queue_actor_ahead INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN queue_delay_seconds INTEGER NOT NULL DEFAULT 0;
